[project]
name = "braandket-circuit"
version = "0.2.6"
description = "A library for working with quantum circuits based on BraAndKet."
readme = "README.md"

requires-python = ">=3.10"
dependencies = [
    "braandket>=0.8.6.post1",
    "zkl-registries@git+https://gitee.com/zhengkeli/zkl-pythonx-registries@v0.2.0"
]

[dependency-groups]
dev = [
    "pytest>=7.4.3",
    "tensorflow>=2.0.0",
]
