[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "braandket-circuit"
version = "0.1.0-dev"
description = "A library for working with quantum circuits based on BraAndKet."
authors = []
readme = "README.md"
packages = [{ include = "braandket_circuit" }]

[tool.poetry.dependencies]
python = "^3.8"
braandket = "^0.8.3"
